### ISSUE TITLE
Feature: User can view all playable characters

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all playable characters
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click on the `Agents` button on the navbar to be directed to the `Agents` page view which will populate a list of playable heroes based off of the items received from the `Valorant API`.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Joseph_Valdez_AJAX_Project1024_1](https://user-images.githubusercontent.com/117682160/211394833-3fd110fc-63a2-4a69-9bd4-17fe295ee415.jpg)

![Joseph_Valdez_AJAX_Project1024_2](https://user-images.githubusercontent.com/117682160/211394892-13ee0739-044f-487a-9927-bd1f57904831.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the `Homepage` page view with proper styling
- [x] Create the `Agents` page view with proper styling and give it the class `hidden` by default
- [x] Add proper CSS pseudoselector rulesets to make sure that the buttons are clickable and have the pointer cursor when hovered over.
- [x] Create proper view swapping code to switch between these page views. 
- [x] Create `click` event listeners for the navbar items to use the view swapping code properly
- [x] Connect the page to the `Valorant API`
- [x] Create a list of items consisting of the Agent's `names` and their `killfeed icons` pulled from the `Valorant API`
- [x] Style the rows so that they alternate in background color and font color
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
