### ISSUE TITLE
Feature: User can filter playable characters by role

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter playable characters by role 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the `Agent` page view, they may click the radio buttons corresponding to different Agent roles. This will generate a new list of playable characters that belong to that role. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Joseph_Valdez_AJAX_Project1024_2](https://user-images.githubusercontent.com/117682160/211395280-ecffc533-bd4a-4c50-ac0d-8334ec44d938.jpg)

![Joseph_Valdez_AJAX_Project1024_3](https://user-images.githubusercontent.com/117682160/211395303-22e4591a-27d4-4c9a-b80f-927691f655b9.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in filter table with functionality
- [x] Make it so that only one button can be clicked at a time
- [x] Allow clicking on the icon (if present) and label to also check the box
- [x] Modify the DOM creation code to only add in characters that meet that role criteria
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
