### ISSUE TITLE
Feature: User can view character abilities and biographies

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view character abilities and biographies
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user is on the `Agent` page view, they may select an agent to bring up the `Individual Agent` page view, which will fill the page with corresponding data, showing their biography and list of abilities. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Joseph_Valdez_AJAX_Project1024_3](https://user-images.githubusercontent.com/117682160/211395802-442dc980-412d-440a-85ef-3ab891d8df38.jpg)

![Joseph_Valdez_AJAX_Project1024_4](https://user-images.githubusercontent.com/117682160/211395810-bc60bf14-106b-4e58-a17b-5718c0ce57b6.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create event listener for the `tbody` targeting the `tr`
- [x] Amend the DOM render function so that it applies an `Id` value corresponding to that agent's name
- [x] Create `individual agent` view in the HTML with proper styling and responsiveness
- [x] Add an event listener to use the viewswap function to go to the `individual agent` view
- [x] Modify the API function to populate the page with corresponding data
- [x] Create exception to the `Passive` ability so that it hides that element if no corresponding ability was found
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
