### ISSUE TITLE
Feature: User can view details about each ability

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details about each ability. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the `Individual Agent` page view, they may click on any of their listed abilities to switch to the `Individual Ability` page view, which will populate relevant details about that ability. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/212378724-1e948812-52a2-42d8-9165-2b4cc0f603b1.png)

![image](https://user-images.githubusercontent.com/117682160/212395290-8a4f33ea-9e5a-471e-a1e6-3e5f24695d23.png)

![image](https://user-images.githubusercontent.com/117682160/212395313-58562806-a5ce-4c91-b1ac-4250a06b1ac4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add `cursor:pointer` to the `ability containers`
- [x] Add event listeners to the `ability containers`
- [x] Create new page view for `individual ability`
- [x] Create handler function to swap to the `individual ability` page view and use the API to fill in the corresponding information 
- [x] Modify responsiveness so portrait shows up with wider viewport widths
- [x] Create back buttons with handlers to go back to the previous page view, which should be either `individual agent` or 'agents' page currently

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
