### ISSUE TITLE
Feature: User can view all usable weapons

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all usable weapons. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/211397456-8c6a5703-7e11-4541-92c2-a11921445257.png)

![image](https://user-images.githubusercontent.com/117682160/212407443-55a27dd6-2909-44f0-bee0-38e138c5471b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create new Navbar item `Weapons`
- [x] Create new page view for `weapons` with proper styling 
- [x] Modify API function to take `weapons` as a parameter and append a proper list of all weapons in the game with proper styling from previous issue in the `agents view`
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
