### ISSUE TITLE
Feature: User can filter usable weapons by type

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter usable weapons by type. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the `Weapons` page view, they can click on the filter radio buttons to repopulate the list with weapons matching that type.  
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/211398066-49aa69a5-dffa-43a7-8899-2e351d5786bd.png)

![image](https://user-images.githubusercontent.com/117682160/211398104-bea42496-7840-4848-9f3c-f659adec2583.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in filter table with functionality
- [x] Make it so that only one button can be clicked at a time
- [x] Modify the DOM creation code to only add in characters that meet that role criteria
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
