### ISSUE TITLE
Feature: User can view specific weapon details

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/Valorant-Checker#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view specific weapon details. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the `Weapons` page view, they can select a weapon which will swap them to the `Individual Weapons` page view to display correlated details about that weapon. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/211398440-53d8ff2c-a86f-46a4-b73b-65d3e0302318.png)

![image](https://user-images.githubusercontent.com/117682160/213268616-87baed71-2a11-49ab-8d72-4c240e30f486.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create new page view for `individual weapons` with proper styling
- [x] Ensure that page view function works with new page view 
- [x] Add new render function to add table in a similar manner to previous page views but for weapon stats
- [x] Add event listeners to the `tr` elements of weapons in the `weapons` page view
- [x] Look through populated stats and removed unecessary ones, such as `shotgun pellet count` for non-shotgun weapons
- [x] See if any data needs to be converted to be easily readable for the user 
- [x] Add a back button to go back to the `weapons` page view
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
